version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: portal_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: portal_eletricista_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portal_network

volumes:
  postgres_data:

networks:
  portal_network:
